import 'dotenv/config.js'

const {
  MONGODB_URI = process.env.NODE_ENV === 'test'
    ? process.env.TEST_MONGODB_URI
    : process.env.DEV_MONGODB_URI || process.env.MONGODB_URI,
  BACKEND_PORT,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  SEMYSMS_API_TOKEN,
  SEMYSMS_DEVICE_ID,
  DOMAIN_NAME,
  SOURCE_EMAIL,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  AT_EXPIRES_IN,
  RT_EXPIRES_IN,
  RT_REFRESH_AFTER_SEC,
  ORDER_POOL_KEY,
  ACCEPTED_HOSTNAME,
  ACCESS_REQUESTED_EXPIRES_IN_DAYS,
  DELETE_ORDERS_AFTER,
  DELETE_ORDERS_MARKED_FOR_DELETION_AFTER,
  VITE_TIMEZONE,
} = process.env

export {
  BACKEND_PORT,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  SEMYSMS_API_TOKEN,
  SEMYSMS_DEVICE_ID,
  DOMAIN_NAME,
  SOURCE_EMAIL,
  MONGODB_URI,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  AT_EXPIRES_IN,
  RT_EXPIRES_IN,
  RT_REFRESH_AFTER_SEC,
  ORDER_POOL_KEY,
  ACCEPTED_HOSTNAME,
  ACCESS_REQUESTED_EXPIRES_IN_DAYS,
  DELETE_ORDERS_AFTER,
  DELETE_ORDERS_MARKED_FOR_DELETION_AFTER,
}

export const TIMEZONE = VITE_TIMEZONE
