require('dotenv').config()

const {
  PORT,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  DOMAIN_NAME,
  MONGODB_URI,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  AT_EXPIRES_IN,
  RT_EXPIRES_IN,
  RT_REFRESH_AFTER_SEC,
} = process.env

module.exports = {
  PORT,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  DOMAIN_NAME,
  MONGODB_URI,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  AT_EXPIRES_IN,
  RT_EXPIRES_IN,
  RT_REFRESH_AFTER_SEC,
}
